server:
  port: 8082

spring:
  application:
    name: product-service  # Ensure this matches what you use in Eureka & Gateway
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: "Priti@123"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
