server:
  port: 8082

spring:
  application:
    name: order-service

resilience4j:
  circuitbreaker:
    instances:
      productService:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 2
        maxWaitDurationInHalfOpenState: 1s
        slidingWindowSize: 10
        minimumNumberOfCalls: 5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
